
services:
  postgres:
    image: postgres:12
    container_name: postgres_db_2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: digital_wallet
    ports:
      - "5430:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - backend_network

  digital_wallet_api:
    build: 
      context: ./DigitalWallet
      dockerfile: Dockerfile 
    container_name: digital_wallet_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_HOST: postgres  
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    ports:
      - "8080:8080"
    networks:
      - backend_network

  digital_wallet_client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080/api
        VITE_WS: ws://localhost:8080/api/users/connect
        VITE_PORT: 5173
    container_name: digital_wallet_client
    depends_on:
      - digital_wallet_api
    ports:
      - "5173:80"
    networks:
      - backend_network
      
networks:
  backend_network:
    driver: bridge

    
volumes:
  postgres_data_2:
