version: "3.8"

services:
  postgres:
    image: postgres:12
    container_name: postgres_db_2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: digital_wallet
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:

